### PR TITLE
Add year input

### PR DESCRIPTION
**Pull request by jbreenali**

### CODE REVIEW

**Comment by MahmoudDiab25** [comment]
@Karyum I rewrite it to how it should be,  how he wrote it at first, how I sow it :sweat_smile:

**Comment by MahmoudDiab25** [comment]
@Karyum put I sow also that he did not change the style of the input that he created, so do not merge it yet.

**Comment by MahmoudDiab25** [comment]
@jbreenali please change the style of the year input to be like other inputs.

**Comment by tawfeek-eg239** [comment]
hello there

**Comment by tawfeek-eg239** [comment]
@Karyum  view the changes

**Review by Karyum — APPROVED** [review]

**Pull request merged**
